config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"

  resources :mech_variants, only: %i[index show]
  resources :lists, except: :destroy do
    resources :list_entries, shallow: true
  end
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  name                :string           not null
#  target_battle_value :integer          not null
#  era_id              :bigint
#  faction_category_id :bigint
#  rules_level_id      :bigint
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  id                  :uuid             not null, primary key
#
class List < ApplicationRecord
  validates :name, :target_battle_value, :default_piloting_skill, :default_gunnery_skill,
    presence: true
  validates :name, uniqueness: true
  validates :target_battle_value,
    numericality: { only_integer: true, greater_than: 0 }
  validates :default_piloting_skill, :default_gunnery_skill,
    numericality: { only_integer: true, greater_than_or_equal:
                    Rails.configuration.MIN_SKILL_VALUE, less_than_or_equal:
                    Rails.configuration.MAX_SKILL_VALUE }

  belongs_to :era, required: false, inverse_of: :lists
  belongs_to :faction_category, required: false, inverse_of: :lists
  belongs_to :rules_level, required: false, inverse_of: :lists

  has_many :list_entries, inverse_of: :list, dependent: :destroy
  has_many :battle_values, through: :list_entries, inverse_of: :lists
  has_many :mech_variants, through: :battle_values, inverse_of: :lists
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.includes(:era, :faction_category, :rules_level).order(updated_at: :desc).limit(10)
  end

  def new
    @list = List.new

    # set defaults
    @list.faction_category = FactionCategory.where(name: "Inner Sphere").first
    @list.rules_level = RulesLevel.where(name: "Advanced").first
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list) }
      else
        flash.now[:alert] = @list.errors.full_messages
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@list, partial: "lists/list_form", locals: { list: @list }) }
      end
    end
  end

  def edit
    @list = List.find(params[:id])

    if @list.nil?
      head :not_found
      return
    end
  end

  def update
    @list =
      List
      .includes(:list_entries, :battle_values, :mech_variants)
      .find_by(id: params[:id])

    if @list.nil?
      head :not_found
      return
    end

    @list.assign_attributes(list_params.except(:list_entries))
    if list_params["list_entries"]
      set_list_entries(@list, list_params["list_entries"])
    end

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list) }
      else
        flash.now[:alert] = @list.errors.full_messages
        format.html { render edit_list_url(@list), status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@list, partial: "lists/list_form", locals: { list: @list }) }
      end
    end
  end

  def show
    @list =
      List
      .includes(
        :list_entries, :battle_values, :mech_variants, :era, :faction_category,
        :rules_level
      )
      .find_by(id: params[:id])
  end

  private

    def list_params
      params.require(:list).permit([
        :name,
        :target_battle_value,
        :era_id,
        :faction_category_id,
        :rules_level_id,
        :default_gunnery_skill,
        :default_piloting_skill,
        list_entries: [
          :id,
          :mech_variant_id,
          :piloting_skill,
          :gunnery_skill,
        ],
      ])
    end

    def set_list_entries(list, list_entry_params)
      destroy_removed_list_entries(list, list_entry_params)
      update_list_entries(list, list_entry_params)
      add_new_list_entries(list, list_entry_params)
    end

    def destroy_removed_list_entries(list, list_entry_params)
      ids_to_keep = list_entry_params.filter_map {|entry| entry["id"] }
      list
        .list_entries
        .filter {|list_entry| !ids_to_keep.include?(list_entry.id) }
        .each {|list_entry| list_entry.destroy }
    end

    def update_list_entries(list, list_entry_params)
      list_entry_params
        .find_all {|entry_params| entry_params["id"] }
        .map do |entry_params|
          list_entry =
            list
            .list_entries
            .find {|list_entry| list_entry.id == entry_params["id"] }

          battle_value = BattleValue.find_by(
            mech_variant: MechVariant.find_by(id: entry_params["mech_variant_id"]),
            piloting_skill: entry_params["piloting_skill"].to_i,
            gunnery_skill: entry_params["gunnery_skill"].to_i,
          )
          list_entry.battle_value = battle_value
        end
    end

    def add_new_list_entries(list, list_entry_params)
      list_entry_params
        .find_all {|entry_params| !entry_params["id"] }
        .map do |entry_params|
          battle_value = BattleValue.find_by(
            mech_variant: MechVariant.find_by(id: entry_params["mech_variant_id"]),
            piloting_skill: entry_params["piloting_skill"].to_i,
            gunnery_skill: entry_params["gunnery_skill"].to_i,
          )
          ListEntry.new(list: list, battle_value: battle_value)
        end
        .each {|list_entry|
          list.list_entries << list_entry
        }
    end
end

app/views/lists/_list_form.html.erb
<% # parameters: %>
<% #   list: a List model whose fields the form will map onto %>

<%= form_with model: list, id: dom_id(list), html: { class: "list-new" } do |form| %>
  <% if list.errors.any? %>
    <div class="notification is-danger is-light">
      <p><%= pluralize(list.errors.count, "error") %>:</p>
      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "List Name:", class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :faction_category_id, "Faction Category:", class: "label" %>
    <div class="control">
      <%= form.collection_select :faction_category_id, FactionCategory.order(id: :asc), :id, :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :rules_level_id, "Rules Level:", class: "label" %>
    <div class="control">
      <%= form.collection_select :rules_level_id, RulesLevel.order(level: :asc), :id, :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :target_battle_value, "Target Battle Value:", class: "label" %>
    <div class="control">
      <%= form.number_field :target_battle_value, value: list.target_battle_value || 5000, min: 500, step: 500, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :default_gunnery_skill, "Default Pilot Gunnery Skill", class: "label" %>
    <div class="control">
      <%= form.number_field :default_gunnery_skill, value: list.default_gunnery_skill || 4, min: Rails.configuration.MIN_SKILL_VALUE, max: Rails.configuration.MAX_SKILL_VALUE, step: 1, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :default_piloting_skill, "Default Pilot Piloting Skill", class: "label" %>
    <div class="control">
      <%= form.number_field :default_piloting_skill, value: list.default_piloting_skill || 5, min: Rails.configuration.MIN_SKILL_VALUE, max: Rails.configuration.MAX_SKILL_VALUE, step: 1, class: "input" %>
    </div>
  </div>

  <div class="field era">
    <div class="button-set">
      <%= form.collection_radio_buttons :era_id, Era.order(start_year: :asc), :id, :name do |button| %>
        <%= content_tag :div, class: "choice-button" do %>
          <%= button.label do %>
            <%= image_tag("era_icons/#{image_filename_for_era(button.text)}") %>
            <%= button.text %>
            <%= button.radio_button %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit class: "button is-link", data: { turbo_frame: "_top" } %>
    </div>
    <% cancel_url = list.persisted? ? list_url(list) : lists_url %>
    <%= link_to("Cancel", cancel_url, class: "button", target: "_top") %>
  </div>
<% end %>

app/views/lists/_list_page_header.html.erb
<%
    # Takes the following parameters:
    #   list: the List for the page
%>
<header class="hero is-primary is-small">
  <div class="hero-body">
    <div class="level">
      <div class="level-item">
        <p class="title"><%= list.name %></p>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Era</p>
          <p class="title"><%= list.era&.name || "All" %></p>
        </div>
      </div>

      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Faction Category</p>
          <p class="title"><%= list.faction_category&.name || "All" %></p>
        </div>
      </div>

      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Rules Level</p>
          <p class="title"><%= list.rules_level&.name || "All" %></p>
        </div>
      </div>

      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Default Pilot</p>
          <p class="title"><%= "#{list.default_gunnery_skill}/#{list.default_piloting_skill}" %></p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/lists/_list_show_main.html.erb
<div id="list-entries" class="columns is-multiline">
  <%= render partial: "list_entries/list_entry", collection: @list.list_entries.order(id: :asc), locals: { compact: false } %>
</div>

<%= link_to "Add Mech", new_list_list_entry_url(@list), class: "button" %>
<%= link_to "Edit List", edit_list_url(@list), class: "button", data: { turbo_frame: "_top" } %>
<%= link_to "Back to Lists Index", lists_url, class: "button", data: { turbo_frame: "_top" } %>

app/views/lists/edit.html.erb
<section class="section">
  <header class="hero is-small">
    <div class="container">
      <p class="title">Edit <%= @list.name %></p>
    </div>
  </header>

  <%= turbo_stream_from "list" %>
  <%= turbo_frame_tag "list" do %>
    <%= render "list_form", list: @list %>
  <% end %>
</section>

app/views/lists/index.html.erb
<section class="section">
  <header class="hero is-small">
    <div class="container">
      <p class="title">Latest Lists</p>
    </div>
  </header>
</section>

<section class="section">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Name</th>
        <th>Faction Category</th>
        <th>Era</th>
        <th>Rules Level</th>
        <th>Target Battle Value</th>
        <th>Created At</th>
        <th>Last Updated At</th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each do |list| %>
        <tr>
          <td><%= link_to list.name, list_url(list) %></td>
          <td><%= list.faction_category&.name || "All" %></td>
          <td><%= list.era&.name || "All" %></td>
          <td><%= list.rules_level&.name || "All" %></td>
          <td><%= number_with_delimiter(list.target_battle_value, delimiter: ",") %> BV</td>
          <td><%= list.created_at.strftime("%b %e, %Y") %></td>
          <td><%= list.updated_at.strftime("%b %e, %Y") %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="8">
          <%= link_to "Create New List", new_list_url, class: "container" %>
        </td>
      </tr>
    </tbody>
  </table>
</section>

app/views/lists/new.html.erb
<section class="section">
  <header class="hero is-small">
    <div class="container">
      <p class="title">New List</p>
    </div>
  </header>

  <%= turbo_stream_from "list" %>
  <%= turbo_frame_tag "list" do %>
    <%= render "list_form", list: @list %>
  <% end %>
</section>

app/views/lists/show.html.erb
<%= render partial: "list_page_header", locals: { list: @list } %>

<section class="main-list-show-section section">
  <%= render partial: "shared/battle_value_display" %>

  <%= turbo_frame_tag :list_show_main do %>
    <% render partial: "list_show_main" %>
  <% end %>
</section>