config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"

  resources :mech_variants, only: %i[index show]
  resources :lists, except: :destroy do
    resources :list_entries, shallow: true
  end
end

app/models/list_entry.rb
# == Schema Information
#
# Table name: list_entries
#
#  id              :bigint           not null, primary key
#  battle_value_id :bigint           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  list_id         :uuid             not null
#
class ListEntry < ApplicationRecord
  belongs_to :list, inverse_of: :list_entries
  belongs_to :battle_value, inverse_of: :list_entries
  has_one :mech_variant, through: :battle_value, inverse_of: :list_entries
end

app/controllers/list_entries_controller.rb
class ListEntriesController < ApplicationController
  def index
  end

  def new
    @list = List.find(params[:list_id])
    @page = page_param(params)
    page_size = Rails.configuration.pagination_page_size

    era_id_filter = @list.era_id if @list.era
    faction_category_id_filter = @list.faction_category_id if @list.faction_category
    rules_level_filter = @list.rules_level_id if @list.rules_level

    @faction_options_for_faction_filter = [Faction.new] + Faction.where(
      faction_category: @list.faction_category,
      availability: { era: @list.era },
    ).joins(availability: :era).distinct.order(id: :asc).all.to_a

    if params[:full_name_filter]
      session[:full_name_filter] = params[:full_name_filter]
    end
    if params[:role_id_filter]
      session[:role_id_filter] = params[:role_id_filter]
    end

    if params[:faction_id_filter]
      session[:faction_id_filter] = params[:faction_id_filter]
    end
    if params[:model_availability_filter]
      session[:model_availability_filter] = params[:model_availability_filter]
    end

    mech_variant_scopes = MechVariant
    at_least_one_mech_variant_filter = false

    if session[:full_name_filter].present?
      at_least_one_mech_variant_filter = true
      mech_variant_scopes =
        mech_variant_scopes.by_full_name(session[:full_name_filter])
    end
    if session[:role_id_filter].present?
      at_least_one_mech_variant_filter = true
      mech_variant_scopes =
        mech_variant_scopes.by_role(session[:role_id_filter])
    end
    if era_id_filter.present?
      at_least_one_mech_variant_filter = true
      mech_variant_scopes =
        mech_variant_scopes.from_era(era_id_filter)
    end
    if faction_category_id_filter.present?
      at_least_one_mech_variant_filter = true
      mech_variant_scopes =
        mech_variant_scopes.from_faction_category(faction_category_id_filter)
    end
    if session[:faction_id_filter].present?
      at_least_one_mech_variant_filter = true
      mech_variant_scopes =
        mech_variant_scopes.from_faction(session[:faction_id_filter])
    end
    if rules_level_filter.present?
      at_least_one_mech_variant_filter = true
      mech_variant_scopes =
        mech_variant_scopes.legal_in_rules_level(rules_level_filter)
    end

    subquery = MechChassis.joins(:mech_variants)
    if at_least_one_mech_variant_filter
      subquery = subquery.merge(mech_variant_scopes)
    end

    if session[:model_availability_filter].present?
      subquery = subquery.by_model_availability(session[:model_availability_filter])
    end

    @chassis_on_this_page =
      MechChassis
      .includes(:mech_variants)
      .joins(:mech_variants)
      .order(tonnage: :asc, name: :asc)
      .where(id:
        subquery
        .group(:id)
        .offset((@page - 1) * page_size)
        .limit(page_size)
        .order("MIN(mech_variants.tonnage) ASC, mech_chassis.name ASC")
      )

    @total_chassis = subquery.distinct(:id).count
    @total_pages = (@total_chassis / page_size.to_f).ceil
    Rails.logger.info "Found #{@total_chassis} matching mech chassis"
  rescue => error
    @chassis_on_this_page = []
    @total_chassis = 0
    @total_pages = 0
    Rails.logger.error error
    # TODO: display error
  end

  def create
    @list_entry = ListEntry.new(allowed_create_params)
    @list = @list_entry.list
    respond_to do |format|
      if @list_entry.save
        format.html { redirect_to @list }
        format.turbo_stream
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new-list-entry-flash", partial: "new_list_entry_flash") }
      end
    end
  end

  def edit
    @list_entry = ListEntry.find(params[:id])
    @type = params[:type] || "gunnery"
    @battle_values = @list_entry.mech_variant.battle_values
    if @type == "gunnery"
      @battle_values = @battle_values.where(piloting_skill: @list_entry.battle_value.piloting_skill).order(gunnery_skill: :desc)
    else
      @battle_values = @battle_values.where(gunnery_skill: @list_entry.battle_value.gunnery_skill).order(piloting_skill: :desc)
    end

    respond_to do |format|
      format.html { render :edit }
      format.turbo_stream { render turbo_stream: turbo_stream.replace("list-entry-card-#{@list_entry.id}", :edit) }
    end
  end

  def update
    @list_entry =
      ListEntry
      .includes(:battle_value, :mech_variant)
      .find_by(id: params[:id])
    @list = @list_entry.list

    if @list_entry.nil?
      head :not_found
      return
    end

    @list_entry.assign_attributes(list_entry_update_params)

    if @list_entry.save
      respond_to do |format|
        format.html { redirect_to list_entry_url(@list_entry) }
        format.turbo_stream
      end
    else
      flash.now[:alert] = @list_entry.errors.full_messages
      respond_to do |format|
        format.html { render edit_list_entry_url(@list_entry), status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("list-entry-card-#{@list_entry.id}", :edit) }
      end
    end
  end

  def show
    @list_entry = ListEntry.find(params[:id])
  end

  def destroy
    @list_entry = ListEntry.find(params[:id])
    @list = @list_entry.list
    @list_entry.destroy
    respond_to do |format|
      format.html { redirect_to @list }
      format.turbo_stream
    end
  end

  private

    def allowed_create_params
      params.require(:list_entry).permit(:list_id, :battle_value_id)
    end

    def list_entry_update_params
      params.require(:list_entry).permit([:battle_value_id])
    end
end

app/views/list_entries/_filter_controls.html.erb
<%= form_with url: new_list_list_entry_url(@list), method: :get do |form| %>
  <%= form.hidden_field :list_id, value: @list.id %>

  <div class="level">
    <span class="field">
      <label class="label" for="mech-chassis-filter-full-name">Name:</label>
      <span class="control">
        <input
          id="mech-chassis-filter-full-name"
          name="full_name_filter"
          class="input"
          type="text"
          value="<%= session[:full_name_filter] || "" %>"
        />
      </span>
    </span>

    <span class="field">
      <span class="control">
        <label class="label" for="mech-chassis-filter-role">Role:</span>
        <div class="select">
          <%= form.collection_select "role_id_filter", [Role.new] + Role.order(id: :asc).all.to_a, :id, :name, id: "mech-chassis-filter-role", selected: session[:role_id_filter] || "" %>
        </div>
      </span>
    </span>

    <span class="field">
      <span class="control">
        <label class="label" for="mech-chassis-filter-faction">Faction:</span>
        <div class="select">
          <%= form.collection_select "faction_id_filter", @faction_options_for_faction_filter, :id, :name, id: "mech-chassis-filter-faction", selected: session[:faction_id_filter] || "" %>
        </div>
      </span>
    </span>

    <span class="field">
      <span class="control">
        <label class="label" for="mech-chassis-filter-model-availability">Model Availability:</span>
        <div class="select">
          <select id="mech-chassis-filter-model-availability" name="model_availability_filter">
            <%= options_for_select({
              "All Mechs" => "",
              "Only mechs with a plastic model" => "plastic_model_exists",
              "Only mechs whose model Brent owns" => "plastic_model_owned",
            }, session[:model_availability_filter] || "") %>
          </select>
        </div>
      </span>
    </span>

    <span class="control">
      <%= form.submit "Apply Filters", class: "button" %>
    </span>

    <span class="control">
      <%= link_to "Cancel", list_url(@list), class: "button is-warning" %>
    </span>
  </div>
<% end %>

app/views/list_entries/_list_entry.html.erb
<% # required parameters:
   #   list_entry: the ListEntry to display
   #
   # optional parameters:
   #   compact: whether to display just mech names instead of names, images, and stats; defaults to false
%>

<% mech = list_entry.mech_variant %>
<% battle_value = list_entry.battle_value %>
<% defined?(compact) or compact = false %>

<%= turbo_frame_tag dom_id(list_entry), class: "column is-3" do %>
  <div class="card list-entry">
    <header class="card-header">
      <p class="card-header-title"><%= mech.full_name %></p>
      <p class="subtitle"><%= mech.tonnage %> ton <%= mech.role.name %></p>
    </header>
    <% if !compact %>
      <div class="card-content">
        <div class="card-image">
          <figure class="image">
            <% chassis_image_url = asset_url(url_for(mech.chassis.image)) %>
            <%= image_tag chassis_image_url, alt: mech.full_name %>
          </figure>
        </div>
        <div class="list_entry_equipment_list">
          <ul>
            <% weapon_list_for_mech(mech).each do |weapon_description| %>
              <li><%= weapon_description %></li>
            <% end %>
            <% non_weapon_equipment_list_for_mech(mech).each do |equipment_description| %>
              <li><%= equipment_description %></li>
            <% end %>
          </ul>
        </div>
        <hr>
        <div class="level">
          <div class="level-item">
            <p><%= battle_value.gunnery_skill %>/<%= battle_value.piloting_skill %> pilot</p>
          </div>
          <div class="level-item">
            <p><%= number_with_delimiter(battle_value.battle_value, delimiter: ",") %> BV</p>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to edit_list_entry_url(list_entry, type: "gunnery"), class: "card-footer-item danger" do %>
            <%= fa_icon "crosshairs" %>
        <% end %>
        <%= link_to edit_list_entry_url(list_entry, type: "piloting"), class: "card-footer-item danger" do %>
            <%= fa_icon "user" %>
        <% end %>
        <div class="card-footer-item">
          <%= button_to "X", list_entry_url(list_entry), method: :delete, class: "button is-danger is-inverted" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/list_entries/_mech_chassis_card.html.erb
<% chassis = mech_chassis_card %>
<%= link_to mech_variants_url(mech_chassis_id: chassis.id, list_id: @list.id, chassis_page: @page), class: "component-mech-picture-list-card" do %>
  <% display_name = chassis.name %>
  <% tonnages = chassis.mech_variants.map(&:tonnage).uniq %>
  <% chassis_image_url = asset_url(url_for(chassis.image)) %>
  <% if chassis.clan_name %>
  <%   display_name += " (#{chassis.clan_name})" %>
  <% end %>
  <%= image_tag chassis_image_url, alt: display_name, class: "component-mech-picture-list-card-image" %>
  <%= content_tag :h2, "#{display_name} #{tonnages.join("/")} tons", class: "component-mech-picture-list-card-title" %>
<% end %>

app/views/list_entries/_mech_chassis_table.html.erb
<%= render "filter_controls" %>
<section class="component-mech-picture-list section">
  <%= render partial: "mech_chassis_card", collection: @chassis_on_this_page %>
</section>
<%= render "pagination" %>

app/views/list_entries/_new_list_entry_flash.html.erb
<section id="new_list_entry_flash" class="section">
  <% if @list_entry.errors.any? %>
    <div class="notification is-danger is-light">
      <p><%= pluralize(@list_entry.errors.count, "error") %>:</p>
      <ul>
        <% @list_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</section>

app/views/list_entries/_pagination.html.erb
<% num_page_links = 15 %>

<% if @total_pages <= num_page_links %>
<%   link_page_range = (1..@total_pages) %>
<% elsif (@page - num_page_links/2) <= 1 %>
<%   link_page_range = (1..num_page_links) %>
<% elsif @page > (@total_pages - num_page_links/2) %>
<%   link_page_range = ((@total_pages - num_page_links)..@total_pages) %>
<% else %>
<%   half_range = num_page_links/2 %>
<%   link_page_range = ((@page - half_range)..(@page + half_range)) %>
<% end %>

<nav class="component-pagination" role="navigation" aria-label="pagination">
  <%= link_to "Previous",
    new_list_list_entry_url(@list, page: @page - 1),
    class: "pagination-previous",
    disabled: @page == 1 %>
  <%= link_to "Next Page",
    new_list_list_entry_url(@list, page: @page + 1),
    class: "pagination-next",
    disabled: @page == @total_pages %>
  <ul class="pagination-list">
    <% if link_page_range.first != 1 %>
      <li>
        <%= link_to "Go to page 1",
          new_list_list_entry_url(@list, page: 1),
          class: "pagination-link",
          aria: { label: "Go to page 1" } %>
      </li>
    <% end %>
    <% if link_page_range.first > 2 %>
      <li>
        <span class="pagination-ellipsis">&hellip;</span>
      </li>
    <% end %>

    <% link_page_range.each do |page_num| %>
    <%   extra_class = (page_num == @page ? "is-current" : "") %>
      <li>
        <%= link_to page_num,
          new_list_list_entry_url(@list, page: page_num),
          class: "pagination-link #{extra_class}",
          aria: { label: "Go to page #{page_num}" } %>
      </li>
    <% end %>

    <% if link_page_range.last != @total_pages %>
      <li>
        <span class="pagination-ellipsis">&hellip;</span>
      </li>
      <li>
        <%= link_to @total_pages,
          new_list_list_entry_url(@list, page: @total_pages),
          class: "pagination-link",
          aria: { label: "Go to page #{@total_pages}" } %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/list_entries/create.turbo_stream.erb
<%= turbo_stream.replace "list_show_main" do %>
  <%= turbo_frame_tag :list_show_main do %>
    <%= render partial: "lists/list_show_main" %>
  <% end %>
<% end %>

<%= turbo_stream.replace "bv_display" do %>
  <%= render partial: "shared/battle_value_display" %>
<% end %>

app/views/list_entries/destroy.turbo_stream.erb
<%= turbo_stream.remove(@list_entry) %>

<%= turbo_stream.replace "bv_display" do %>
  <%= render partial: "shared/battle_value_display" %>
<% end %>

app/views/list_entries/edit.html.erb
<% mech = @list_entry.mech_variant %>

<%= turbo_frame_tag dom_id(@list_entry), class: "column is-3" do %>
  <%= form_with model: @list_entry, id: dom_id(@list_entry) do |form| %>
    <div class="card list-entry">
      <header class="card-header">
        <div class="level">
          <div class="level-item">
            <p class="card-header-title"><%= mech.full_name %></p>
          </div>
          <div class="level-item">
            <p><%= mech.tonnage %> ton <%= mech.role.name %></p>
          </div>
        </div>
      </header>
      <div class="card-content">
        <div class="field">
          <% if @type == "gunnery" %>
            <%= form.label :battle_value_id, "Gunnery Skill:", class: "label" %>
          <% else %>
            <%= form.label :battle_value_id, "Piloting Skill:", class: "label" %>
          <% end %>
          <div class="control">
            <% if @type == "gunnery" %>
              <%= form.collection_select :battle_value_id, @battle_values, :id, ->(bv) { "#{bv.gunnery_skill} (#{sprintf("%+d", bv.battle_value - @list_entry.battle_value.battle_value)} BV)" }, class: "input" %>
            <% else %>
              <%= form.collection_select :battle_value_id, @battle_values, :id, ->(bv) { "#{bv.piloting_skill} (#{sprintf("%+d", bv.battle_value - @list_entry.battle_value.battle_value)} BV)" }, class: "input" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="card-footer-item">
          <%= form.submit "Submit", class: "button is-ghost" %>
        </div>
        <%= link_to "Cancel", list_entry_url(@list_entry), class: "card-footer-item" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/list_entries/new.html.erb
<%= turbo_frame_tag :list_show_main do %>
  <div id="list-entries" class="columns is-multiline">
    <%= render partial: "list_entries/list_entry", collection: @list.list_entries, locals: { compact: true } %>
  </div>

  <%= render "mech_chassis_table" %>
<% end %>

app/views/list_entries/show.html.erb
<%= render partial: "list_entry", locals: { list_entry: @list_entry } %>

app/views/list_entries/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@list_entry) do %>
  <%= render partial: "list_entry", locals: { list_entry: @list_entry } %>
<% end %>

<%= turbo_stream.replace "bv_display" do %>
  <%= render partial: "shared/battle_value_display" %>
<% end %>