config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"

  resources :mech_variants, only: %i[index show]
  resources :lists, except: :destroy do
    resources :list_entries, shallow: true
  end
end

app/models/mech_variant.rb
# == Schema Information
#
# Table name: mech_variants
#
#  id                 :integer          not null, primary key
#  tonnage            :integer          not null
#  base_battle_value  :integer          not null
#  cbill_cost         :integer
#  rules_level_id     :integer          not null
#  year_introduced    :integer          not null
#  mul_url            :text             not null
#  heat_sinks         :string           not null
#  walking_mp         :integer          not null
#  jumping_mp         :integer          not null
#  front_armor        :integer          not null
#  rear_armor         :integer          not null
#  engine_model       :string           not null
#  structure_type     :string           not null
#  armor_type         :string           not null
#  mech_chassis_id    :integer          not null
#  omnimech           :boolean          default(FALSE), not null
#  designation        :string           not null
#  technology_base_id :bigint           not null
#  role_id            :bigint
#  full_name          :text             not null
#

class MechVariant < ApplicationRecord
  validates :full_name, :designation, :tonnage, :base_battle_value,
    :year_introduced, :mul_url, :heat_sinks, :walking_mp, :jumping_mp,
    :front_armor, :rear_armor, :engine_model, :structure_type, :armor_type,
    presence: true
  validates :full_name, :mul_url, uniqueness: true
  validates :designation, uniqueness: { scope: [:mech_chassis_id] }
  validates :tonnage, :base_battle_value, numericality:
    { only_integer: true, greater_than: 0 }
  validates :cbill_cost, numericality:
    { only_integer: true, greater_than: 0, allow_nil: true }
  validates :year_introduced, numericality: { only_integer: true }
  validates :walking_mp, :jumping_mp, :front_armor, :rear_armor, numericality:
    { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :chassis, class_name: "MechChassis", foreign_key:
    :mech_chassis_id, inverse_of: :mech_variants
  belongs_to :rules_level, optional: false, inverse_of: :mech_variants
  belongs_to :technology_base, optional: false, inverse_of: :mech_variants
  belongs_to :role, optional: true, inverse_of: :mech_variants

  has_many :mech_source_books, inverse_of: :mech_variant, dependent: :destroy
  has_many(
    :source_books,
    through: :mech_source_books,
    inverse_of: :mech_variants,
  )
  has_many :availability, inverse_of: :mech_variant, dependent: :destroy
  has_many :eras, through: :availability, inverse_of: :mech_variants
  has_many :factions, through: :availability, inverse_of: :mech_variants
  has_many :battle_values, inverse_of: :mech_variant, dependent: :destroy
  has_many :mech_equipment, inverse_of: :mech_variant, dependent: :destroy
  has_many :equipment, through: :mech_equipment, inverse_of: :mech_variants
  has_many :list_entries, through: :battle_values, inverse_of: :mech_variant
  has_many :lists, through: :list_entries, inverse_of: :mech_variants

  def total_armor
    front_armor + rear_armor
  end

  # scopes

  def self.by_full_name(full_name)
    where("mech_variants.full_name ILIKE ?", "%#{full_name}%")
  end

  def self.by_role(role_id)
    where(role_id: role_id)
  end

  def self.from_era(era_id)
    joins(:availability)
    .where(availability: { era_id: era_id })
  end

  def self.from_faction_category(faction_category_id)
    joins([availability: [:faction]])
    .where({
      availability: {
        factions: { faction_category_id: faction_category_id },
      },
    })
  end

  def self.from_faction(faction_id)
    joins(:availability)
    .where(availability: { faction_id: faction_id })
  end

  def self.legal_in_rules_level(level)
    joins(:rules_level)
      .where(rules_levels: { level: ..level })
  end

  # end scopes

  def weapons
    mech_equipment
      .joins(:equipment)
      .includes(:equipment)
      .where(equipment: { weapon: true })
      .order('equipment.name ASC')
  end

  def non_weapon_equipment
    mech_equipment
      .joins(:equipment)
      .includes(:equipment)
      .where(equipment: { weapon: false })
      .order('equipment.name ASC')
  end
end

app/controllers/mech_variants_controller.rb
class MechVariantsController < ApplicationController
  def index
    @list = List.find(params[:list_id])
    @mech_chassis = MechChassis.find(params[:mech_chassis_id])
    mech_chassis_id_filter = @mech_chassis.id
    @chassis_page = page_param(params, :chassis_page)

    era_id_filter = @list.era_id if @list.era
    faction_category_id_filter = @list.faction_category_id if @list.faction_category_id
    rules_level_filter = @list.rules_level_id if @list.rules_level_id

    @mechs = MechVariant.distinct.where(mech_chassis_id: @mech_chassis)

    if session[:role_id_filter].present?
      @mechs = @mechs.by_role(session[:role_id_filter])
    end
    if era_id_filter.present?
      @mechs = @mechs.from_era(era_id_filter)
    end
    if faction_category_id_filter.present?
      @mechs =
        @mechs.from_faction_category(faction_category_id_filter)
    end
    if session[:faction_id_filter].present?
      @mechs = @mechs.from_faction(session[:faction_id_filter])
    end
    if rules_level_filter.present?
      @mechs =
        @mechs.legal_in_rules_level(rules_level_filter)
    end

    @mech_variants =
      @mechs
      .includes([:chassis, :role, :battle_values])
      .joins(:chassis)
      .select("mech_variants.*, mech_chassis.name")
      .order(Arel.sql(<<~ORDER_BY))
        mech_variants.tonnage ASC, mech_variants.year_introduced ASC,
        mech_variants.designation ASC
      ORDER_BY
  rescue => error
    @mech_variants = []
    Rails.logger.error error
    # TODO: display error
  end
end

app/views/mech_variants/_mech_variant_table.html.erb
<%
  # parameters:
  #   mech_variants
%>

<section class="component-mech-table-list section">
  <table class="table is-striped is-narrow is-fullwidth is-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tonnage</th>
        <th>Role</th>
        <th>Weapons</th>
        <th>Heat Sinks</th>
        <th>Equipment</th>
        <th>Armor (Front/Rear)</th>
        <th>Movement</th>
        <th>Jumping</th>
        <th>Add to List</th>
      </tr>
    </thead>
    <tbody>
      <% if mech_variants.empty? %>
        <tr>
          <td colSpan="9" class="component-mech-table-list-empty-placeholder">
            No mechs match the current filters.
          </td>
        </tr>
      <% else %>
        <%= render partial: "mech_variant_table_row", collection: mech_variants %>
      <% end %>
    </tbody>
  </table>
</section>

app/views/mech_variants/_mech_variant_table_row.html.erb
<% mech = mech_variant_table_row %>
<tr class="component-mech-list-card">
  <td>
    <%
      # TODO: implement link to mech show page
      #<Link to={`/mechs/${props.id}`}>
      #  {props.fullName}
      #</Link>
    %>
    <%= mech.full_name %>
  </td>
  <td><%= mech.tonnage %> tons</td>
  <td><%= mech.role&.name || "None" %></td>
  <td>
    <ul>
      <% weapon_list_for_mech(mech).each do |weapon_description| %>
        <li><%= weapon_description %></li>
      <% end %>
    </ul>
  </td>
  <td>
    <%= mech.heat_sinks %>
  </td>
  <td>
    <ul>
      <% mech.mech_equipment.select { |mech_equipment| !mech_equipment.equipment.weapon }.each do |mech_equipment| %>
      <%  text = mech_equipment.equipment.name %>
      <%  if mech_equipment.count > 1 %>
      <%    text += " x#{mech_equipment.count}" %>
      <%  end %>
        <li><%= text %></li>
      <% end %>
    </ul>
  </td>
  <td>
    <% total_armor = mech.front_armor + mech.rear_armor %>
    <%= "#{total_armor} (#{mech.front_armor}/#{mech.rear_armor})" %>
  </td>
  <td>
    <% running_mp = (mech.walking_mp * 1.5).ceil %>
    <%= "#{mech.walking_mp}/#{running_mp}" %>
  </td>
  <td>
    <%= "#{mech.jumping_mp == 0 ? "-" : mech.jumping_mp}" %>
  </td>
  <td class="component-mech-list-card-add-to-list-column">
    <% battle_value = battle_value_for_mech_variant(mech, @list.default_gunnery_skill, @list.default_piloting_skill) %>
    <% list_entry = ListEntry.new(list: @list, battle_value: battle_value) %>
    <%= form_with model: list_entry, url: list_list_entries_url(@list) do |form| %>
      <%= form.hidden_field :list_id %>
      <%= form.hidden_field :battle_value_id %>
      <%
        bv_remaining_after_purchase = battle_value_remaining(@list) - battle_value.battle_value
        link_color = if bv_remaining_after_purchase >= 0
                       "is-primary"
                     else
                       "is-danger"
                     end
      %>
      <%= form.submit "#{number_with_delimiter(battle_value.battle_value, delimiter: ",")} BV", class: "button #{link_color} is-light" %>
    <% end %>
  </td>
</tr>

app/views/mech_variants/index.html.erb
<%= turbo_frame_tag :list_show_main do %>
  <section class="section">
    <div class="component-mech-table-list-container">

      <% chassis_image_url = asset_url(url_for(@mech_chassis.image)) %>
      <%= content_tag :div, class: "component-mech-table-list-background", style: "background-image: url(#{chassis_image_url})"  do %>
      <% end %>

      <div class="container"><%= link_to "Back to Chassis List", new_list_list_entry_url(@list, page: @chassis_page), class: "button is-info", style: "display: block; margin-left: auto; margin-right: auto;" %></div>
    
      <%= render partial: "mech_variant_table", locals: { mech_variants: @mech_variants } %>
    </div>
  </section>
<% end %>